### ISSUE TITLE
Make error handling PhoneGap / file access ready

### ISSUE THREAD

**Issue by X-Tender** [abraaobuenotype/type#10]
**Issue**
When using your lib in a PIXIJS Project which gets deployed in PhoneGap it doesn gets loaded because you check for `response.status !== 200`. In case of PhoneGap the font gets loaded via file scheme access so the status code is `0`.

**Solution**
update the check to `/*if (request.status !== 200 && request.status !== 0) {`

**Comment by abraaobuenotype** [comment]
hello, you can try working with the fonts in binary using the workAroundLoad method
ex.

loader.workAroundLoad('fontName', new Uint8Array(fontData).buffer);
loader.load(true) //it is necessary to pass the argument true

hope it works. Thank you ^-^

**Comment by X-Tender** [comment]
I will give it a try. Thank you.
