### ISSUE TITLE
Typescript definitions. What will it take to create those?

### ISSUE THREAD

**Issue by pokebadgerswithspoon** [abraaobuenotype/type#5]
Hello.

Trying PIXI with typescript and it looks great.
It would be nice to have some typescript definitions for your module.
Do you have plans to create such definitions, or probably already have it somewhere around? 
Or could you hint where to start the development?
I did my first attempt to implement it, but it failed with "ReferenceError: type is not defined" error from the browser debugger. 

#### type-for-pixi.d.ts
```
declare namespace type {
    const VERSION: string;
    namespace text {
        class TextField {
            constructor(w: number, h:number);
        }
    }
}
//tslint:disable-next-line:no-single-declare-module
declare module "type-for-pixi" {
    export = type;
}
```
```
import * as type from 'type-for-pixi'
...
new type.text.TextField(100,100); <-- does not work, "ReferenceError: type is not defined"
....

**Comment by abraaobuenotype** [comment]
First, thank you for using our framework.
We have no plans for Typescript, we use ES6 + in development.
It would be great to get contributions, feel free to create a branch and add improvements.
