### ISSUE TITLE
font is undefined

### ISSUE THREAD

**Issue by rtalon83** [abraaobuenotype/type#7]
Hi!

I'm testing the code in Chrome and Firefox. In Chrome I haven't problem but in Firefox I have a unknown error.

TypeError: font is undefined.

Updating ( F5 ) the page, sometime it's ok but sometime it's error.

**Comment by abraaobuenotype** [comment]
thanks for using the type.
Could you please send the font you are using and some prints

**Comment by rtalon83** [comment]
In this moment the 1.7.5 version.

I have a japanese font: Meiryo.ttf ( 8.3 MB ) and another error:

`downloadable font: OS/2: Bad version number, setting it to 1: 4 (font-family: "japonesa testfont" style:normal weight:normal stretch:normal src index:0) source: data:application/x-font-ttf;base64,AAEAAAAKAIAAAwAgT1MvMgAAAAAAAACsAAAAWGNtYXAAAAAAAAABBAAAACxnbHlmAAAAAAAAATAAAAAQaGVhZAAAAAAAA … AAAAAAAAAAAAAAAIAAAAAQAAAAIAAQABAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAIAHgADAAEECQABAAAAAAADAAEECQACAAIAAAAAAAEAAAAAAAAAAAAAAAAAAA==`

         
```
var loader = new type.Loader();       
            loader.add('japonesa', 'Meiryo.ttf');       
            loader.once('loadComplete', init);
            loader.load();

           // more code....... //

            var japonesaText = new type.text.TextField(800, 800);
            japonesaText.setText('<japonesa>マルチプライヤ</japonesa>',
            {
                align: 'left',

                japonesa: {
                    fontFamily: "japonesa",
                    fontSize: 40,
                    fill: "blue",
                    dropShadow: false,
                    dropShadowColor: '#0000GG'
                }
            });
 
            stage.addChild(japonesaText);
```

**Comment by abraaobuenotype** [comment]
Hi,

I include in the examples a template folder using the font that you submitted. The model worked well. Do not forget that for the correct operation, you need to run from a server.

**Comment by rtalon83** [comment]
Ohh!!! Thanks!!
