### ISSUE TITLE
Anti-alias/smoothing options?

### ISSUE THREAD

**Issue by jazzyjeff5** [abraaobuenotype/type#8]
Thanks a lot for producing this library!

Are there any options for adjusting the anti aliasing of the rendered font? I'm creating some text sized 22, and it looks quite soft/blurry at that size, and gets even worse with smaller font sizes. Can the anti aliasing be adjusted? If not is this something you might add in the future?

Thank you!

**Comment by abraaobuenotype** [comment]
Could you send me an example?

**Comment by abraaobuenotype** [comment]
closed due to lack of interaction
