### ISSUE TITLE
Softkeyboard

### ISSUE THREAD

**Issue by PRonnenberg** [abraaobuenotype/type#9]
Thanks for your great contribution!
Are there any plans when to add softkeyboards for mobiles?
Do you have any hints how to implement the softkeyboard or do you have a dev preview for it?
Thank you very much, kind regards

**Comment by abraaobuenotype** [comment]
yes ... we are implementing, but we still have no date for the release. To implement a softkeyboard the idea is a bit simple, but it does a bit of work, just create a layout of a keyboard and identify which position the user touched and transfer the string to the input.
